import { Stage } from '../types/curriculum';

export const CURRICULUM_STAGES: Stage[] = [
  {
    id: 1,
    title: 'Stage 1: Home Row Haven',
    subtitle: 'Where every typing journey begins!',
    description: 'Learn the foundational home row keys and feel the tactile bumps on F and J.',
    icon: '🌸',
    color: 'from-emerald-400 to-green-500',
    lessons: [
      {
        id: 'stage-1-lesson-1',
        stageId: 1,
        stageLessonNumber: 1,
        title: 'The Pointer Bumps',
        subtitle: 'Feel the little bumps on F and J with your pointer fingers',
        type: 'new-keys',
        newKeys: ['f', 'j', ' '],
        practiceText: 'f j f j ff jj f f j j fj jf f j ff jj fjf jfj',
        targetWpm: 6,
        minAccuracy: 85,
        rewardCoins: 25,
        rewardXp: 30,
      },
      {
        id: 'stage-1-lesson-2',
        stageId: 1,
        stageLessonNumber: 2,
        title: 'Middle Finger Neighbors',
        subtitle: 'Meet D and K right next to your pointer fingers',
        type: 'new-keys',
        newKeys: ['d', 'k'],
        practiceText: 'd k d k fd jk dk kd f d j k ff dd jj kk fdk jkd',
        targetWpm: 8,
        minAccuracy: 85,
        rewardCoins: 30,
        rewardXp: 40,
      },
      {
        id: 'stage-1-lesson-3',
        stageId: 1,
        stageLessonNumber: 3,
        title: 'Ring Finger Friends',
        subtitle: 'Add S and L to widen your reach across the row',
        type: 'new-keys',
        newKeys: ['s', 'l'],
        practiceText: 's l s l as df jkl sl ls fs jl sf lj sdk lfs slsl',
        targetWpm: 10,
        minAccuracy: 88,
        rewardCoins: 35,
        rewardXp: 45,
      },
      {
        id: 'stage-1-lesson-4',
        stageId: 1,
        stageLessonNumber: 4,
        title: 'Pinky Explorers',
        subtitle: 'Wake up your pinkies on A and the semicolon key',
        type: 'new-keys',
        newKeys: ['a', ';'],
        practiceText: 'a ; a ; asdf jkl; a; ;a fa ja sa la da ka asdf; lkja',
        targetWpm: 12,
        minAccuracy: 88,
        rewardCoins: 40,
        rewardXp: 50,
      },
      {
        id: 'stage-1-lesson-5',
        stageId: 1,
        stageLessonNumber: 5,
        title: 'Home Row Word Magic',
        subtitle: 'Combine all home row letters into real cozy words',
        type: 'words',
        newKeys: ['h', 'g'],
        practiceText: 'all sad dad glad fall flash salad hall half ask flask',
        targetWpm: 14,
        minAccuracy: 90,
        rewardCoins: 50,
        rewardXp: 60,
      },
      {
        id: 'stage-1-lesson-6',
        stageId: 1,
        stageLessonNumber: 6,
        title: 'Home Row Haven Champion',
        subtitle: 'Complete your first stage and rescue Mochi Kitten!',
        type: 'story',
        newKeys: [],
        practiceText: 'a glad dad had a flask of salad as all fell fast',
        targetWpm: 16,
        minAccuracy: 90,
        rewardCoins: 75,
        rewardXp: 100,
        unlockAnimalId: 'kitten',
      },
    ],
  },
  {
    id: 2,
    title: 'Stage 2: Top Row Treks',
    subtitle: 'Reaching high into the sunny treetops!',
    description: 'Learn the top row vowels E, I, O, U and consonants R, T, Y, W, Q, P.',
    icon: '🍃',
    color: 'from-sky-400 to-blue-500',
    lessons: [
      {
        id: 'stage-2-lesson-1',
        stageId: 2,
        stageLessonNumber: 1,
        title: 'Pointer Reaches Up',
        subtitle: 'Reach your pointer fingers up to R and U',
        type: 'new-keys',
        newKeys: ['r', 'u'],
        practiceText: 'r u fr ju fur ruf red rug run jar far fur fun run rub',
        targetWpm: 16,
        minAccuracy: 88,
        rewardCoins: 35,
        rewardXp: 45,
      },
      {
        id: 'stage-2-lesson-2',
        stageId: 2,
        stageLessonNumber: 2,
        title: 'The Great Vowels: E & I',
        subtitle: 'Middle fingers stretch up to the two most popular vowels',
        type: 'new-keys',
        newKeys: ['e', 'i'],
        practiceText: 'de ki ed ik see like ride hide kid side feed feel leaf',
        targetWpm: 18,
        minAccuracy: 90,
        rewardCoins: 40,
        rewardXp: 50,
      },
      {
        id: 'stage-2-lesson-3',
        stageId: 2,
        stageLessonNumber: 3,
        title: 'Ring Reaches: W & O',
        subtitle: 'Ring fingers stretch up to W and O',
        type: 'new-keys',
        newKeys: ['w', 'o'],
        practiceText: 'sw lo owl wow slow glow flow show word work wood look',
        targetWpm: 20,
        minAccuracy: 90,
        rewardCoins: 45,
        rewardXp: 55,
      },
      {
        id: 'stage-2-lesson-4',
        stageId: 2,
        stageLessonNumber: 4,
        title: 'The Center Stretch: T & Y',
        subtitle: 'Index fingers stretch up and over to T and Y',
        type: 'new-keys',
        newKeys: ['t', 'y'],
        practiceText: 'ft jy try toy tree they stay yesterday tiny true tasty',
        targetWpm: 20,
        minAccuracy: 90,
        rewardCoins: 45,
        rewardXp: 55,
      },
      {
        id: 'stage-2-lesson-5',
        stageId: 2,
        stageLessonNumber: 5,
        title: 'Pinky Heights: Q & P',
        subtitle: 'Delicate pinkies stretch up to Q and P',
        type: 'new-keys',
        newKeys: ['q', 'p'],
        practiceText: 'aq ;p quick puppy park petal tulip quiet play pond path',
        targetWpm: 22,
        minAccuracy: 90,
        rewardCoins: 50,
        rewardXp: 60,
      },
      {
        id: 'stage-2-lesson-6',
        stageId: 2,
        stageLessonNumber: 6,
        title: 'Treetop Master Trial',
        subtitle: 'Type top row sentences and welcome Rusty Fox!',
        type: 'story',
        newKeys: [],
        practiceText: 'the sweet yellow kite flew high over the leafy tree park',
        targetWpm: 24,
        minAccuracy: 92,
        rewardCoins: 80,
        rewardXp: 110,
        unlockAnimalId: 'fox',
      },
    ],
  },
  {
    id: 3,
    title: 'Stage 3: Bottom Row Beach',
    subtitle: 'Diving down into sandy shores and clear waters!',
    description: 'Learn bottom row letters V, M, C, X, Z and essential punctuation , and .',
    icon: '🏖️',
    color: 'from-amber-400 to-orange-500',
    lessons: [
      {
        id: 'stage-3-lesson-1',
        stageId: 3,
        stageLessonNumber: 1,
        title: 'Pointers Down: V & M',
        subtitle: 'Curl your pointer fingers down to V and M',
        type: 'new-keys',
        newKeys: ['v', 'm'],
        practiceText: 'fv jm vim rim vam moved river warm summer velvet moves',
        targetWpm: 22,
        minAccuracy: 90,
        rewardCoins: 45,
        rewardXp: 55,
      },
      {
        id: 'stage-3-lesson-2',
        stageId: 3,
        stageLessonNumber: 2,
        title: 'Middle Down: C and Comma',
        subtitle: 'Middle fingers curl down to C and the comma key',
        type: 'new-keys',
        newKeys: ['c', ','],
        practiceText: 'dc k, cat, camp, cup, nice, clean, cool, calm, ocean,',
        targetWpm: 24,
        minAccuracy: 90,
        rewardCoins: 50,
        rewardXp: 60,
      },
      {
        id: 'stage-3-lesson-3',
        stageId: 3,
        stageLessonNumber: 3,
        title: 'Ring Down: X and Period',
        subtitle: 'Ring fingers curl down to X and the full stop period',
        type: 'new-keys',
        newKeys: ['x', '.'],
        practiceText: 'sx l. six. box. fix. fox. relax. extra. exciting. calm.',
        targetWpm: 25,
        minAccuracy: 90,
        rewardCoins: 50,
        rewardXp: 60,
      },
      {
        id: 'stage-3-lesson-4',
        stageId: 3,
        stageLessonNumber: 4,
        title: 'Pinky Down: Z and Slash',
        subtitle: 'Pinkies curl down to Z and the slash key',
        type: 'new-keys',
        newKeys: ['z', '/'],
        practiceText: 'az ;/ zero zip zoo breeze fuzzy pizza dazzle cozy maze',
        targetWpm: 25,
        minAccuracy: 90,
        rewardCoins: 55,
        rewardXp: 65,
      },
      {
        id: 'stage-3-lesson-5',
        stageId: 3,
        stageLessonNumber: 5,
        title: 'The Full Pangram Safari',
        subtitle: 'Type sentences that use every single letter of the alphabet!',
        type: 'sentences',
        newKeys: ['b', 'n'],
        practiceText: 'the quick brown fox jumps over the lazy dog by the calm river.',
        targetWpm: 28,
        minAccuracy: 92,
        rewardCoins: 85,
        rewardXp: 120,
        unlockAnimalId: 'panda',
      },
    ],
  },
  {
    id: 4,
    title: 'Stage 4: Capital Cliffs',
    subtitle: 'Reaching higher with Shift keys and proper names!',
    description: 'Master left and right Shift keys for beautiful capital letters.',
    icon: '⛰️',
    color: 'from-purple-400 to-indigo-500',
    lessons: [
      {
        id: 'stage-4-lesson-1',
        stageId: 4,
        stageLessonNumber: 1,
        title: 'Right Shift for Left Hand Letters',
        subtitle: 'Hold Right Shift with pinky while left hand types',
        type: 'new-keys',
        newKeys: ['A', 'S', 'D', 'F', 'G', 'R', 'E', 'W', 'Q', 'T'],
        practiceText: 'Apple Sun Day Fox Green Red Water Quiet Tree Great',
        targetWpm: 26,
        minAccuracy: 90,
        rewardCoins: 50,
        rewardXp: 60,
      },
      {
        id: 'stage-4-lesson-2',
        stageId: 4,
        stageLessonNumber: 2,
        title: 'Left Shift for Right Hand Letters',
        subtitle: 'Hold Left Shift with pinky while right hand types',
        type: 'new-keys',
        newKeys: ['H', 'J', 'K', 'L', 'U', 'I', 'O', 'P', 'N', 'M'],
        practiceText: 'Home Joy Kite Lily Moon Night Owl Panda River Pine',
        targetWpm: 28,
        minAccuracy: 90,
        rewardCoins: 55,
        rewardXp: 65,
      },
      {
        id: 'stage-4-lesson-3',
        stageId: 4,
        stageLessonNumber: 3,
        title: 'Animal Sanctuary Roll Call',
        subtitle: 'Type the names of all our lovely island friends',
        type: 'words',
        newKeys: [],
        practiceText: 'Barnaby Bunny, Mochi Kitten, Rusty Fox, and Bao Bao Panda.',
        targetWpm: 30,
        minAccuracy: 92,
        rewardCoins: 65,
        rewardXp: 80,
      },
      {
        id: 'stage-4-lesson-4',
        stageId: 4,
        stageLessonNumber: 4,
        title: 'Capital Cliffs Master',
        subtitle: 'Full sentences with sparkling capital letters and Pip Penguin!',
        type: 'story',
        newKeys: [],
        practiceText: 'Every Morning, The Sunny Island Welcomes New Animal Friends With Joy.',
        targetWpm: 32,
        minAccuracy: 93,
        rewardCoins: 90,
        rewardXp: 130,
        unlockAnimalId: 'penguin',
      },
    ],
  },
  {
    id: 5,
    title: 'Stage 5: Number & Symbol Safari',
    subtitle: 'Numbers, exclamation marks, questions, and quotes!',
    description: 'Extend your reach to the top number row and everyday punctuation.',
    icon: '🧭',
    color: 'from-pink-400 to-rose-500',
    lessons: [
      {
        id: 'stage-5-lesson-1',
        stageId: 5,
        stageLessonNumber: 1,
        title: 'Numbers 1 Through 5',
        subtitle: 'Left hand stretches to 1, 2, 3, 4, and 5',
        type: 'new-keys',
        newKeys: ['1', '2', '3', '4', '5'],
        practiceText: '1 2 3 4 5 12 34 51 234 543 15 24 35 12345 54321',
        targetWpm: 28,
        minAccuracy: 90,
        rewardCoins: 55,
        rewardXp: 65,
      },
      {
        id: 'stage-5-lesson-2',
        stageId: 5,
        stageLessonNumber: 2,
        title: 'Numbers 6 Through 0',
        subtitle: 'Right hand stretches to 6, 7, 8, 9, and 0',
        type: 'new-keys',
        newKeys: ['6', '7', '8', '9', '0'],
        practiceText: '6 7 8 9 0 67 89 90 789 60 70 80 90 100 2026',
        targetWpm: 30,
        minAccuracy: 90,
        rewardCoins: 60,
        rewardXp: 70,
      },
      {
        id: 'stage-5-lesson-3',
        stageId: 5,
        stageLessonNumber: 3,
        title: 'Exclamations and Questions',
        subtitle: 'Shift + 1 for ! and Shift + / for ?',
        type: 'new-keys',
        newKeys: ['!', '?', "'", '"'],
        practiceText: 'Look here! What is that? "It is Barnaby!" Pip cheered happily!',
        targetWpm: 32,
        minAccuracy: 92,
        rewardCoins: 70,
        rewardXp: 85,
      },
      {
        id: 'stage-5-lesson-4',
        stageId: 5,
        stageLessonNumber: 4,
        title: 'Professor Hoot Scholar Exam',
        subtitle: 'Combine numbers, symbols, and words to unlock Professor Hoot!',
        type: 'story',
        newKeys: [],
        practiceText: 'In 2026, we counted 10 rabbits, 5 kittens, and 12 glowing stars!',
        targetWpm: 35,
        minAccuracy: 93,
        rewardCoins: 100,
        rewardXp: 150,
        unlockAnimalId: 'owl',
      },
    ],
  },
  {
    id: 6,
    title: 'Stage 6: Sight Word Woods',
    subtitle: 'Unlocking high-speed muscle memory for common words!',
    description: 'Practice the most common English words, digraphs, and rhythm combinations.',
    icon: '🌲',
    color: 'from-emerald-500 to-teal-600',
    lessons: [
      {
        id: 'stage-6-lesson-1',
        stageId: 6,
        stageLessonNumber: 1,
        title: 'The Great Digraphs',
        subtitle: 'Smooth two-letter combinations: th, sh, ch, wh, ing',
        type: 'words',
        newKeys: [],
        practiceText: 'the this that then shine fresh beach chair where white singing wishing',
        targetWpm: 38,
        minAccuracy: 92,
        rewardCoins: 65,
        rewardXp: 80,
      },
      {
        id: 'stage-6-lesson-2',
        stageId: 6,
        stageLessonNumber: 2,
        title: 'Top 50 Sight Words',
        subtitle: 'Words that appear in almost every book and story',
        type: 'words',
        newKeys: [],
        practiceText: 'there have been many people who said they could see the small green boat',
        targetWpm: 42,
        minAccuracy: 93,
        rewardCoins: 75,
        rewardXp: 90,
      },
      {
        id: 'stage-6-lesson-3',
        stageId: 6,
        stageLessonNumber: 3,
        title: 'Flow & Rhythm Sentences',
        subtitle: 'Type continuously without hesitating on common phrases',
        type: 'sentences',
        newKeys: [],
        practiceText: 'We found a quiet clearing in the woods where the sunshine was warm and bright.',
        targetWpm: 45,
        minAccuracy: 94,
        rewardCoins: 85,
        rewardXp: 100,
      },
      {
        id: 'stage-6-lesson-4',
        stageId: 6,
        stageLessonNumber: 4,
        title: 'The Zen of Cappy Capybara',
        subtitle: 'Stay calm and relaxed at high speed to unlock Cappy!',
        type: 'story',
        newKeys: [],
        practiceText: 'Cappy sat by the warm mineral bath, smiling as waterlilies drifted past the stone bridge.',
        targetWpm: 48,
        minAccuracy: 95,
        rewardCoins: 110,
        rewardXp: 160,
        unlockAnimalId: 'capybara',
      },
    ],
  },
  {
    id: 7,
    title: 'Stage 7: Storybook Shire',
    subtitle: 'Charming tales of adventure and friendship!',
    description: 'Extended full paragraphs to build speed endurance and narrative flow.',
    icon: '📖',
    color: 'from-blue-500 to-indigo-600',
    lessons: [
      {
        id: 'stage-7-lesson-1',
        stageId: 7,
        stageLessonNumber: 1,
        title: 'The Secret Meadow Garden',
        subtitle: 'A tale of wildflowers, butterflies, and morning tea',
        type: 'story',
        newKeys: [],
        practiceText: 'Behind the tall cedar fence lay a hidden garden full of lavender and sweet mint. Barnaby hopped through the wooden gate, carrying a basket of freshly picked wild strawberries.',
        targetWpm: 50,
        minAccuracy: 94,
        rewardCoins: 90,
        rewardXp: 120,
      },
      {
        id: 'stage-7-lesson-2',
        stageId: 7,
        stageLessonNumber: 2,
        title: 'The Starlight Treehouse',
        subtitle: 'A cozy evening gathering high up in the oak branches',
        type: 'story',
        newKeys: [],
        practiceText: 'Lanterns swayed softly beneath the treehouse roof, casting golden patterns on the wooden deck. All seven animals gathered around the low cedar table to share warm tea and honey biscuits.',
        targetWpm: 55,
        minAccuracy: 95,
        rewardCoins: 100,
        rewardXp: 140,
      },
      {
        id: 'stage-7-lesson-3',
        stageId: 7,
        stageLessonNumber: 3,
        title: 'The Crystal Rapids Race',
        subtitle: 'Ride the river with Ollie Otter and earn your speed stripes!',
        type: 'speed-sprint',
        newKeys: [],
        practiceText: 'The river sparkled like diamond dust in the afternoon sun. Ollie plunged into the crystal waters, spinning playfully as water droplets flew into the cool autumn air.',
        targetWpm: 60,
        minAccuracy: 95,
        rewardCoins: 125,
        rewardXp: 180,
        unlockAnimalId: 'otter',
      },
    ],
  },
  {
    id: 8,
    title: 'Stage 8: 100+ WPM Mastery Rush',
    subtitle: 'The pinnacle speed realm for typing champions!',
    description: 'Challenging high-speed passages, tricky double-letters, and 100+ WPM trials.',
    icon: '⚡',
    color: 'from-amber-500 to-rose-600',
    lessons: [
      {
        id: 'stage-8-lesson-1',
        stageId: 8,
        stageLessonNumber: 1,
        title: 'Double Letter Velocity Sprint',
        subtitle: 'Maintain unbroken rhythm across rapid repeating letters',
        type: 'speed-sprint',
        newKeys: [],
        practiceText: 'Butterflies flutter across shimmering blossom trees as little puppies scramble happily through mossy cobblestones.',
        targetWpm: 70,
        minAccuracy: 95,
        rewardCoins: 110,
        rewardXp: 160,
      },
      {
        id: 'stage-8-lesson-2',
        stageId: 8,
        stageLessonNumber: 2,
        title: 'The 80 WPM Warp Speed Gate',
        subtitle: 'Push past 80 words per minute with pinpoint accuracy',
        type: 'speed-sprint',
        newKeys: [],
        practiceText: 'Lightning fast keystrokes danced across the mechanical switches with effortless precision and rhythmic musical perfection.',
        targetWpm: 80,
        minAccuracy: 96,
        rewardCoins: 130,
        rewardXp: 200,
      },
      {
        id: 'stage-8-lesson-3',
        stageId: 8,
        stageLessonNumber: 3,
        title: 'The 90 WPM Velocity Dash',
        subtitle: 'Nearly triple-digit speed with flawless touch typing flow',
        type: 'speed-sprint',
        newKeys: [],
        practiceText: 'A brilliant burst of sparkling stardust illuminated the whole horizon as the cosmic rocket ship accelerated smoothly beyond the speed of sound.',
        targetWpm: 90,
        minAccuracy: 96,
        rewardCoins: 150,
        rewardXp: 250,
      },
      {
        id: 'stage-8-lesson-4',
        stageId: 8,
        stageLessonNumber: 4,
        title: 'The 100+ WPM Grandmaster Trial',
        subtitle: 'Achieve triple-digit speed and awaken Sparky Baby Dragon!',
        type: 'speed-sprint',
        newKeys: [],
        practiceText: 'With wings outstretched and eyes shimmering like molten gold, the legendary dragon soared over the emerald sanctuary, celebrating every brave typist who achieved total mastery of the keyboard.',
        targetWpm: 100,
        minAccuracy: 96,
        rewardCoins: 300,
        rewardXp: 500,
        unlockAnimalId: 'dragon',
      },
    ],
  },
];

export function findLessonById(lessonId: string) {
  for (const stage of CURRICULUM_STAGES) {
    for (const lesson of stage.lessons) {
      if (lesson.id === lessonId) {
        return { stage, lesson };
      }
    }
  }
  return null;
}

export function getNextLessonId(currentLessonId: string): string | null {
  let foundCurrent = false;
  for (const stage of CURRICULUM_STAGES) {
    for (const lesson of stage.lessons) {
      if (foundCurrent) {
        return lesson.id;
      }
      if (lesson.id === currentLessonId) {
        foundCurrent = true;
      }
    }
  }
  return null;
}
